# lab.conf
router[0]="A"
router[bridged]="true"  # <—— Esto habilita el acceso a internet
router[sysctl]="net.ipv6.conf.all.forwarding=1"

pc[0]="A"
pc[bridged]="true"  # <—— Esto habilita el acceso a internet
pc[sysctl]="net.ipv6.conf.eth0.accept_ra=2"
pc[sysctl]="net.ipv6.conf.eth0.autoconf=1"

#habilitar wireshark
wireshark[bridged]=true
wireshark[port]="3000:3000/tcp"
wireshark[image]="lscr.io/linuxserver/wireshark"
